# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
jobs:
  build-lambda00:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/repo
    environment:
      lambda_name: "00-AuthorizeUser"
    steps:
      - checkout
      - restore_cache:
          keys:
            - lambda-{{ .Branch }}-{{ checksum "lambda/00-AuthorizeUser/index.py" }}-{{ checksum "lambda/requirements.txt" }}
      - run: shopt -s dotglob
      - run:
          command: |
            cd ~/repo/lambda/$lambda_name
            python3 -m pip install -r ~/repo/lambda/requirements.txt -t .
      - save_cache:
          paths:
            - ~/repo/lambda/$lambda_name
          key: lambda-{{ .Branch }}-{{ checksum "lambda/00-AuthorizeUser/index.py" }}-{{ checksum "lambda/requirements.txt" }}
      - run:
          command: |
            cd ~/repo/lambda/$lambda_name
            zip -r $lambda_name.zip  *
            cp *.zip ~
      - persist_to_workspace:
          root: ~/
          paths: 00-AuthorizeUser.zip
  build-lambda01:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/repo
    environment:
      lambda_name: "01-CheckInputs"
    steps:
      - checkout
      - restore_cache:
          keys:
            - lambda-{{ .Branch }}-{{ checksum "lambda/01-CheckInputs/index.py" }}-{{ checksum "lambda/requirements.txt" }}
      - run: shopt -s dotglob
      - run:
          command: |
            cd ~/repo/lambda/$lambda_name
            python3 -m pip install -r ~/repo/lambda/requirements.txt -t .
      - save_cache:
          paths:
            - ~/repo/lambda/$lambda_name
          key: lambda-{{ .Branch }}-{{ checksum "lambda/01-CheckInputs/index.py" }}-{{ checksum "lambda/requirements.txt" }}
      - run:
          command: |
            cd ~/repo/lambda/$lambda_name
            zip -r $lambda_name.zip  *
            cp *.zip ~
      - persist_to_workspace:
          root: ~/
          paths: 01-CheckInputs.zip
  build-lambda02:
    docker:
    - image: circleci/python:3.6
    working_directory: ~/repo
    environment:
      lambda_name: "02-UseExistingSnapshot"
    steps:
    - checkout
    - restore_cache:
        keys:
        - lambda-{{ .Branch }}-{{ checksum "lambda/02-UseExistingSnapshot/index.py" }}-{{ checksum "lambda/requirements.txt" }}
    - run: shopt -s dotglob
    - run:
        command: |
          cd ~/repo/lambda/$lambda_name
          python3 -m pip install -r ~/repo/lambda/requirements.txt -t .
    - save_cache:
        paths:
        - ~/repo/lambda/$lambda_name
        key: lambda-{{ .Branch }}-{{ checksum "lambda/02-UseExistingSnapshot/index.py" }}-{{ checksum "lambda/requirements.txt" }}
    - run:
        command: |
          cd ~/repo/lambda/$lambda_name
          zip -r $lambda_name.zip  *
          cp *.zip ~
    - persist_to_workspace:
        root: ~/
        paths: 02-UseExistingSnapshot.zip
  build-lambda03:
    docker:
    - image: circleci/python:3.6
    working_directory: ~/repo
    environment:
      lambda_name: "03-CheckForSnapshotCompletion"
    steps:
    - checkout
    - restore_cache:
        keys:
        - lambda-{{ .Branch }}-{{ checksum "lambda/03-CheckForSnapshotCompletion/index.py" }}-{{ checksum "lambda/requirements.txt" }}
    - run: shopt -s dotglob
    - run:
        command: |
          cd ~/repo/lambda/$lambda_name
          python3 -m pip install -r ~/repo/lambda/requirements.txt -t .
    - save_cache:
        paths:
        - ~/repo/lambda/$lambda_name
        key: lambda-{{ .Branch }}-{{ checksum "lambda/03-CheckForSnapshotCompletion/index.py" }}-{{ checksum "lambda/requirements.txt" }}
    - run:
        command: |
          cd ~/repo/lambda/$lambda_name
          zip -r $lambda_name.zip  *
          cp *.zip ~
    - persist_to_workspace:
        root: ~/
        paths: 03-CheckForSnapshotCompletion.zip
  build-lambda04:
    docker:
    - image: circleci/python:3.6
    working_directory: ~/repo
    environment:
      lambda_name: "04-ShareSnapshots"
    steps:
    - checkout
    - restore_cache:
        keys:
        - lambda-{{ .Branch }}-{{ checksum "lambda/04-ShareSnapshots/index.py" }}-{{ checksum "lambda/requirements.txt" }}
    - run: shopt -s dotglob
    - run:
        command: |
          cd ~/repo/lambda/$lambda_name
          python3 -m pip install -r ~/repo/lambda/requirements.txt -t .
    - save_cache:
        paths:
        - ~/repo/lambda/$lambda_name
        key: lambda-{{ .Branch }}-{{ checksum "lambda/04-ShareSnapshots/index.py" }}-{{ checksum "lambda/requirements.txt" }}
    - run:
        command: |
          cd ~/repo/lambda/$lambda_name
          zip -r $lambda_name.zip  *
          cp *.zip ~
    - persist_to_workspace:
        root: ~/
        paths: 04-ShareSnapshots.zip
  build-lambda05:
    docker:
    - image: circleci/python:3.6
    working_directory: ~/repo
    environment:
      lambda_name: "05-CopySharedDBSnapshots"
    steps:
    - checkout
    - restore_cache:
        keys:
        - lambda-{{ .Branch }}-{{ checksum "lambda/05-CopySharedDBSnapshots/index.py" }}-{{ checksum "lambda/requirements.txt" }}
    - run: shopt -s dotglob
    - run:
        command: |
          cd ~/repo/lambda/$lambda_name
          python3 -m pip install -r ~/repo/lambda/requirements.txt -t .
    - save_cache:
        paths:
        - ~/repo/lambda/$lambda_name
        key: lambda-{{ .Branch }}-{{ checksum "lambda/05-CopySharedDBSnapshots/index.py" }}-{{ checksum "lambda/requirements.txt" }}
    - run:
        command: |
          cd ~/repo/lambda/$lambda_name
          zip -r $lambda_name.zip  *
          cp *.zip ~
    - persist_to_workspace:
        root: ~/
        paths: 05-CopySharedDBSnapshots.zip
  build-lambda06:
    docker:
    - image: circleci/python:3.6
    working_directory: ~/repo
    environment:
      lambda_name: "06-CheckForDestinationSnapshotCompletion"
    steps:
    - checkout
    - restore_cache:
        keys:
        - lambda-{{ .Branch }}-{{ checksum "lambda/06-CheckForDestinationSnapshotCompletion/index.py" }}-{{ checksum "lambda/requirements.txt" }}
    - run: shopt -s dotglob
    - run:
        command: |
          cd ~/repo/lambda/$lambda_name
          python3 -m pip install -r ~/repo/lambda/requirements.txt -t .
    - save_cache:
        paths:
        - ~/repo/lambda/$lambda_name
        key: lambda-{{ .Branch }}-{{ checksum "lambda/06-CheckForDestinationSnapshotCompletion/index.py" }}-{{ checksum "lambda/requirements.txt" }}
    - run:
        command: |
          cd ~/repo/lambda/$lambda_name
          zip -r $lambda_name.zip  *
          cp *.zip ~
    - persist_to_workspace:
        root: ~/
        paths: 06-CheckForDestinationSnapshotCompletion.zip
  build-lambda07:
    docker:
    - image: circleci/python:3.6
    working_directory: ~/repo
    environment:
      lambda_name: "07-RestoreDatabases"
    steps:
    - checkout
    - restore_cache:
        keys:
        - lambda-{{ .Branch }}-{{ checksum "lambda/07-RestoreDatabases/index.py" }}-{{ checksum "lambda/requirements.txt" }}
    - run: shopt -s dotglob
    - run:
        command: |
          cd ~/repo/lambda/$lambda_name
          python3 -m pip install -r ~/repo/lambda/requirements.txt -t .
    - save_cache:
        paths:
        - ~/repo/lambda/$lambda_name
        key: lambda-{{ .Branch }}-{{ checksum "lambda/07-RestoreDatabases/index.py" }}-{{ checksum "lambda/requirements.txt" }}
    - run:
        command: |
          cd ~/repo/lambda/$lambda_name
          zip -r $lambda_name.zip  *
          cp *.zip ~
    - persist_to_workspace:
        root: ~/
        paths: 07-RestoreDatabases.zip
  build-lambda08:
    docker:
    - image: circleci/python:3.6
    working_directory: ~/repo
    environment:
      lambda_name: "08-CheckForRestoreCompletion"
    steps:
    - checkout
    - restore_cache:
        keys:
        - lambda-{{ .Branch }}-{{ checksum "lambda/08-CheckForRestoreCompletion/index.py" }}-{{ checksum "lambda/requirements.txt" }}
    - run: shopt -s dotglob
    - run:
        command: |
          cd ~/repo/lambda/$lambda_name
          python3 -m pip install -r ~/repo/lambda/requirements.txt -t .
    - save_cache:
        paths:
        - ~/repo/lambda/$lambda_name
        key: lambda-{{ .Branch }}-{{ checksum "lambda/08-CheckForRestoreCompletion/index.py" }}-{{ checksum "lambda/requirements.txt" }}
    - run:
        command: |
          cd ~/repo/lambda/$lambda_name
          zip -r $lambda_name.zip  *
          cp *.zip ~
    - persist_to_workspace:
        root: ~/
        paths: 08-CheckForRestoreCompletion.zip
  build-lambda09a:
    docker:
    - image: circleci/python:3.6
    working_directory: ~/repo
    environment:
      lambda_name: "09a-CreateFargate"
    steps:
    - checkout
    - restore_cache:
        keys:
        - lambda-{{ .Branch }}-{{ checksum "lambda/09a-CreateFargate/index.py" }}-{{ checksum "lambda/requirements.txt" }}
    - run: shopt -s dotglob
    - run:
        command: |
          cd ~/repo/lambda/$lambda_name
          python3 -m pip install -r ~/repo/lambda/requirements.txt -t .
    - save_cache:
        paths:
        - ~/repo/lambda/$lambda_name
        key: lambda-{{ .Branch }}-{{ checksum "lambda/09a-CreateFargate/index.py" }}-{{ checksum "lambda/requirements.txt" }}
    - run:
        command: |
          cd ~/repo/lambda/$lambda_name
          zip -r $lambda_name.zip  *
          cp *.zip ~
    - persist_to_workspace:
        root: ~/
        paths: 09a-CreateFargate.zip
  build-lambda09b:
    docker:
    - image: circleci/python:3.6
    working_directory: ~/repo
    environment:
      lambda_name: "09b-CreateECS"
    steps:
    - checkout
    - restore_cache:
        keys:
        - lambda-{{ .Branch }}-{{ checksum "lambda/09b-CreateECS/index.py" }}-{{ checksum "lambda/requirements.txt" }}
    - run: shopt -s dotglob
    - run:
        command: |
          cd ~/repo/lambda/$lambda_name
          python3 -m pip install -r ~/repo/lambda/requirements.txt -t .
    - save_cache:
        paths:
        - ~/repo/lambda/$lambda_name
        key: lambda-{{ .Branch }}-{{ checksum "lambda/09b-CreateECS/index.py" }}-{{ checksum "lambda/requirements.txt" }}
    - run:
        command: |
          cd ~/repo/lambda/$lambda_name
          zip -r $lambda_name.zip  *
          cp *.zip ~
    - persist_to_workspace:
        root: ~/
        paths: 09b-CreateECS.zip
  build-lambda10:
    docker:
    - image: circleci/python:3.6
    working_directory: ~/repo
    environment:
      lambda_name: "10-TakeSnapshot"
    steps:
    - checkout
    - restore_cache:
        keys:
        - lambda-{{ .Branch }}-{{ checksum "lambda/10-TakeSnapshot/index.py" }}-{{ checksum "lambda/requirements.txt" }}
    - run: shopt -s dotglob
    - run:
        command: |
          cd ~/repo/lambda/$lambda_name
          python3 -m pip install -r ~/repo/lambda/requirements.txt -t .
    - save_cache:
        paths:
        - ~/repo/lambda/$lambda_name
        key: lambda-{{ .Branch }}-{{ checksum "lambda/10-TakeSnapshot/index.py" }}-{{ checksum "lambda/requirements.txt" }}
    - run:
        command: |
          cd ~/repo/lambda/$lambda_name
          zip -r $lambda_name.zip  *
          cp *.zip ~
    - persist_to_workspace:
        root: ~/
        paths: 10-TakeSnapshot.zip
  build-lambda11:
    docker:
    - image: circleci/python:3.6
    working_directory: ~/repo
    environment:
      lambda_name: "11-CheckFinalSnapshotAvailability"
    steps:
    - checkout
    - restore_cache:
        keys:
        - lambda-{{ .Branch }}-{{ checksum "lambda/11-CheckFinalSnapshotAvailability/index.py" }}-{{ checksum "lambda/requirements.txt" }}
    - run: shopt -s dotglob
    - run:
        command: |
          cd ~/repo/lambda/$lambda_name
          python3 -m pip install -r ~/repo/lambda/requirements.txt -t .
    - save_cache:
        paths:
        - ~/repo/lambda/$lambda_name
        key: lambda-{{ .Branch }}-{{ checksum "lambda/11-CheckFinalSnapshotAvailability/index.py" }}-{{ checksum "lambda/requirements.txt" }}
    - run:
        command: |
          cd ~/repo/lambda/$lambda_name
          zip -r $lambda_name.zip  *
          cp *.zip ~
    - persist_to_workspace:
        root: ~/
        paths: 11-CheckFinalSnapshotAvailability.zip
  build-lambda12:
    docker:
    - image: circleci/python:3.6
    working_directory: ~/repo
    environment:
      lambda_name: "12-CleanupAndTagging"
    steps:
    - checkout
    - restore_cache:
        keys:
        - lambda-{{ .Branch }}-{{ checksum "lambda/12-CleanupAndTagging/index.py" }}-{{ checksum "lambda/requirements.txt" }}
    - run: shopt -s dotglob
    - run:
        command: |
          cd ~/repo/lambda/$lambda_name
          python3 -m pip install -r ~/repo/lambda/requirements.txt -t .
    - save_cache:
        paths:
        - ~/repo/lambda/$lambda_name
        key: lambda-{{ .Branch }}-{{ checksum "lambda/12-CleanupAndTagging/index.py" }}-{{ checksum "lambda/requirements.txt" }}
    - run:
        command: |
          cd ~/repo/lambda/$lambda_name
          zip -r $lambda_name.zip  *
          cp *.zip ~
    - persist_to_workspace:
        root: ~/
        paths: 12-CleanupAndTagging.zip
  build-error:
    docker:
    - image: circleci/python:3.6
    working_directory: ~/repo
    environment:
      lambda_name: "ErrorHandlingAndCleanup"
    steps:
    - checkout
    - restore_cache:
        keys:
        - lambda-{{ .Branch }}-{{ checksum "lambda/ErrorHandlingAndCleanup/index.py" }}-{{ checksum "lambda/requirements.txt" }}
    - run: shopt -s dotglob
    - run:
        command: |
          cd ~/repo/lambda/$lambda_name
          python3 -m pip install -r ~/repo/lambda/requirements.txt -t .
    - save_cache:
        paths:
        - ~/repo/lambda/$lambda_name
        key: lambda-{{ .Branch }}-{{ checksum "lambda/ErrorHandlingAndCleanup/index.py" }}-{{ checksum "lambda/requirements.txt" }}
    - run:
        command: |
          cd ~/repo/lambda/$lambda_name
          zip -r $lambda_name.zip  *
          cp *.zip ~
    - persist_to_workspace:
        root: ~/
        paths: ErrorHandlingAndCleanup.zip
  build-final-zip:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Create a Zip of Zips
          command: |
            cd ~
            mkdir lambdas
            cp *.zip lambdas
            zip -r lambdas *
      - store_artifacts:
          path: ~/lambdas.zip
workflows:
  version: 2
  Example_Workflow:
    jobs:
    - build-lambda00
    - build-lambda01
    - build-lambda02
    - build-lambda03
    - build-lambda04
    - build-lambda05
    - build-lambda06
    - build-lambda07
    - build-lambda09a
    - build-lambda09b
    - build-lambda10
    - build-lambda11
    - build-lambda12
    - build-error
    - build-final-zip:
        requires:
          - build-lambda00
          - build-lambda01
          - build-lambda02
          - build-lambda03
          - build-lambda04
          - build-lambda05
          - build-lambda06
          - build-lambda07
          - build-lambda09a
          - build-lambda09b
          - build-lambda10
          - build-lambda11
          - build-lambda12
          - build-error
